/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviegui;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author riley
 */
public class MovieTicket_Frame extends javax.swing.JFrame {

    /**
     * Creates new form MovieTicket_Frame
     */
    public MovieTicket_Frame() {
        initComponents();
        setTitle("MOVIE TICKETS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovieLBL = new javax.swing.JLabel();
        MovieComboBox = new javax.swing.JComboBox<>();
        TicketNumberLBL = new javax.swing.JLabel();
        txt_TicketNumber = new javax.swing.JTextField();
        TicketPriceLBL = new javax.swing.JLabel();
        PriceTxt = new javax.swing.JTextField();
        ReportLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportTxt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_File = new javax.swing.JMenu();
        MenuItem_Exit = new javax.swing.JMenuItem();
        Menu_Tools = new javax.swing.JMenu();
        MenuItem_Process = new javax.swing.JMenuItem();
        MenuItem_Clear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MovieLBL.setText("MOVIE:");

        MovieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napoleon", "Oppenheimer", "Damsel" }));
        MovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieComboBoxActionPerformed(evt);
            }
        });

        TicketNumberLBL.setText("NUMBER OF TICKETS:");

        txt_TicketNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TicketNumberActionPerformed(evt);
            }
        });

        TicketPriceLBL.setText("TICKET PRICE:");

        PriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTxtActionPerformed(evt);
            }
        });

        ReportLBL.setText("TICKET REPORT:");

        ReportTxt.setColumns(20);
        ReportTxt.setRows(5);
        jScrollPane2.setViewportView(ReportTxt);

        Menu_File.setText("File");

        MenuItem_Exit.setText("Exit");
        MenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ExitActionPerformed(evt);
            }
        });
        Menu_File.add(MenuItem_Exit);

        jMenuBar1.add(Menu_File);

        Menu_Tools.setText("Tools");

        MenuItem_Process.setText("Process");
        MenuItem_Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ProcessActionPerformed(evt);
            }
        });
        Menu_Tools.add(MenuItem_Process);

        MenuItem_Clear.setText("Clear");
        MenuItem_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ClearActionPerformed(evt);
            }
        });
        Menu_Tools.add(MenuItem_Clear);

        jMenuBar1.add(Menu_Tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MovieLBL)
                            .addComponent(TicketNumberLBL)
                            .addComponent(TicketPriceLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PriceTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TicketNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MovieComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReportLBL)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovieLBL)
                    .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketNumberLBL)
                    .addComponent(txt_TicketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketPriceLBL)
                    .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(ReportLBL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TicketNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TicketNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TicketNumberActionPerformed

    private void PriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTxtActionPerformed

    private void MovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieComboBoxActionPerformed

    private void MenuItem_ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ProcessActionPerformed
        
        try 
        {
            String movieName = MovieComboBox.getSelectedItem().toString();
            int numberOfTickets = Integer.parseInt(txt_TicketNumber.getText());
            double ticketPrice = Double.parseDouble(PriceTxt.getText());
            
            String output = "";
            
            MovieTicketData md = new MovieTicketData(movieName, numberOfTickets, ticketPrice);
            
            MovieTickets mt = new MovieTickets();
            
            if(mt.ValidateData(md) == true)
            {
                double totalPrice = mt.CalculateTotalTicketPrice(numberOfTickets, ticketPrice);
                
                output = "MOVIE NAME: " + movieName + "\n"
                + "MOVIE TICKET PRICE: R" + ticketPrice + "\n"
                + "NUMBER OF TICKETS: " + numberOfTickets + "\n"
                + "TOTAL TICKET PRICE: R" + totalPrice;
            }
            
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid input! Check your entries.");
                return;
            }
            
            ReportTxt.setText(output);
            
            FileWriter writer = new FileWriter("report.txt", true);
            
            writer.write("\nMOVIE TICKET REPORT \n"
                    + "*********************************** \n"
                    + output + "\n"
                    + "***********************************\n");
            writer.close();
            
            JOptionPane.showMessageDialog(this, "Record saved successfully");
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage());
        }
    }//GEN-LAST:event_MenuItem_ProcessActionPerformed

    private void MenuItem_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ClearActionPerformed
        txt_TicketNumber.setText("");
        PriceTxt.setText("");
        ReportTxt.setText("");
    }//GEN-LAST:event_MenuItem_ClearActionPerformed

    private void MenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit?",
            "Exit Confirmation",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuItem_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicket_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_Clear;
    private javax.swing.JMenuItem MenuItem_Exit;
    private javax.swing.JMenuItem MenuItem_Process;
    private javax.swing.JMenu Menu_File;
    private javax.swing.JMenu Menu_Tools;
    private javax.swing.JComboBox<String> MovieComboBox;
    private javax.swing.JLabel MovieLBL;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JLabel ReportLBL;
    private javax.swing.JTextArea ReportTxt;
    private javax.swing.JLabel TicketNumberLBL;
    private javax.swing.JLabel TicketPriceLBL;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_TicketNumber;
    // End of variables declaration//GEN-END:variables
}
