
package com.mycompany.estateapp;

// JFrame Form

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

// Where the GUI app runs
public class EstateAgentReport extends javax.swing.JFrame {

    /**
     * Creates new form EstateAgentReport
     */
    public EstateAgentReport() {
        initComponents();
        setTitle("Estate Agent Report");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Location = new javax.swing.JLabel();
        Lbl_AgentName = new javax.swing.JLabel();
        Lbl_ProperyPrice = new javax.swing.JLabel();
        Lbl_Commission = new javax.swing.JLabel();
        Lbl_AgentReport = new javax.swing.JLabel();
        ComboBox_Location = new javax.swing.JComboBox<>();
        Txt_AgentName = new javax.swing.JTextField();
        Txt_PropertyPrice = new javax.swing.JTextField();
        Txt_Commission = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_AgentReport = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBar_File = new javax.swing.JMenu();
        MenuItem_Exit = new javax.swing.JMenuItem();
        MenuBar_Tools = new javax.swing.JMenu();
        MenuItem_ProcessReport = new javax.swing.JMenuItem();
        MenuItem_Clear = new javax.swing.JMenuItem();
        MenuItem_Save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_Location.setText("AGENT LOCATION:");

        Lbl_AgentName.setText("ESTATE AGENT NAME:");

        Lbl_ProperyPrice.setText("PROPERTY PRICE:");

        Lbl_Commission.setText("COMMISSION PERCENTAGE:");

        Lbl_AgentReport.setText("ESTATE AGENT REPORT:");

        ComboBox_Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Pretoria" }));

        Txt_AgentReport.setColumns(20);
        Txt_AgentReport.setRows(5);
        jScrollPane1.setViewportView(Txt_AgentReport);

        MenuBar_File.setText("File");

        MenuItem_Exit.setText("Exit");
        MenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ExitActionPerformed(evt);
            }
        });
        MenuBar_File.add(MenuItem_Exit);

        jMenuBar1.add(MenuBar_File);

        MenuBar_Tools.setText("Tools");

        MenuItem_ProcessReport.setText("Process Report");
        MenuItem_ProcessReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ProcessReportActionPerformed(evt);
            }
        });
        MenuBar_Tools.add(MenuItem_ProcessReport);

        MenuItem_Clear.setText("Clear");
        MenuItem_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ClearActionPerformed(evt);
            }
        });
        MenuBar_Tools.add(MenuItem_Clear);

        MenuItem_Save.setText("Save");
        MenuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_SaveActionPerformed(evt);
            }
        });
        MenuBar_Tools.add(MenuItem_Save);

        jMenuBar1.add(MenuBar_Tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Location)
                            .addComponent(Lbl_AgentName)
                            .addComponent(Lbl_ProperyPrice)
                            .addComponent(Lbl_Commission)
                            .addComponent(Lbl_AgentReport))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Location, 0, 145, Short.MAX_VALUE)
                            .addComponent(Txt_AgentName)
                            .addComponent(Txt_PropertyPrice)
                            .addComponent(Txt_Commission))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Location))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_AgentName)
                    .addComponent(Txt_AgentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_ProperyPrice)
                    .addComponent(Txt_PropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Commission)
                    .addComponent(Txt_Commission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Lbl_AgentReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to close application 
    private void MenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to exit?",
        "Exit Confirmation",
        JOptionPane.YES_NO_OPTION
        );
        
        if(confirm == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuItem_ExitActionPerformed

    // Method to clear text fields
    private void MenuItem_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ClearActionPerformed
        Txt_AgentName.setText("");
        Txt_PropertyPrice.setText("");
        Txt_Commission.setText("");
        Txt_AgentReport.setText("");
    }//GEN-LAST:event_MenuItem_ClearActionPerformed

    // Method to process report
    private void MenuItem_ProcessReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ProcessReportActionPerformed
        String agentLocation = ComboBox_Location.getSelectedItem().toString();
        String agentName = Txt_AgentName.getText();
        String price = Txt_PropertyPrice.getText();
        String commissionRate = Txt_Commission.getText();
        
        String output = "";
        
        Data d = new Data(agentLocation, agentName, Double.parseDouble(price), Double.parseDouble(commissionRate));
        EstateAgent e = new EstateAgent();
        
        // Output for report
        if(e.ValidateData(d) == true)
        {
            double commissionPay = e.CalculateCommission(price, commissionRate);
            
            output = "AGENT LOCATION: " + d.getAgentLocation() + "\n"
                    +"AGENT NAME: " + d.getAgentName() + "\n"
                    +"PROPERTY PRICE: R" + d.getPropertyPrice() + "\n"
                    +"COMMISSION PERCENTAGE: " + d.getAgentCommission() + "%" + "\n"
                    +"CALCULATED COMMISSION: R" + String.format("%.2f", commissionPay);
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Check your entries.");
        }
        
        // Shows where to output the report
        Txt_AgentReport.setText(output);
    }//GEN-LAST:event_MenuItem_ProcessReportActionPerformed

    // Method to save report as txt.file
    private void MenuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_SaveActionPerformed
        
        try 
        {
        String agentLocation = ComboBox_Location.getSelectedItem().toString();
        String agentName = Txt_AgentName.getText();
        String price = Txt_PropertyPrice.getText();
        String commissionRate = Txt_Commission.getText();
        
        String output = "";
        
        Data d = new Data(agentLocation, agentName, Double.parseDouble(price), Double.parseDouble(commissionRate));
        EstateAgent e = new EstateAgent();
        
        // Output report
        if(e.ValidateData(d) == true)
        {
            double commissionPay = e.CalculateCommission(price, commissionRate);
            
            output = "AGENT LOCATION: " + d.getAgentLocation() + "\n"
                    +"AGENT NAME: " + d.getAgentName() + "\n"
                    +"PROPERTY PRICE: R" + d.getPropertyPrice() + "\n"
                    +"COMMISSION PERCENTAGE: " + d.getAgentCommission() + "%" + "\n"
                    +"CALCULATED COMMISSION: R" + String.format("%.2f", commissionPay);
        }
        
        // Implementing FileWriter to write txt file
        FileWriter writer = new FileWriter("report.txt", true);
        
        // writes report on the file and saves it
        writer.write("\nESTATE AGENT REPORT \n"
        + "************************************ \n"
        + output + "\n"
        + "************************************ \n");
        
        writer.close();
        
        JOptionPane.showMessageDialog(this, "Record saved successfully!");
        }
        
        // Catch
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage());
        }
    }//GEN-LAST:event_MenuItem_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstateAgentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Location;
    private javax.swing.JLabel Lbl_AgentName;
    private javax.swing.JLabel Lbl_AgentReport;
    private javax.swing.JLabel Lbl_Commission;
    private javax.swing.JLabel Lbl_Location;
    private javax.swing.JLabel Lbl_ProperyPrice;
    private javax.swing.JMenu MenuBar_File;
    private javax.swing.JMenu MenuBar_Tools;
    private javax.swing.JMenuItem MenuItem_Clear;
    private javax.swing.JMenuItem MenuItem_Exit;
    private javax.swing.JMenuItem MenuItem_ProcessReport;
    private javax.swing.JMenuItem MenuItem_Save;
    private javax.swing.JTextField Txt_AgentName;
    private javax.swing.JTextArea Txt_AgentReport;
    private javax.swing.JTextField Txt_Commission;
    private javax.swing.JTextField Txt_PropertyPrice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
